<?php

/**
 * Verify the three package manifests against the source tree, the changelog and the API documentation.
 *
 * `resources/public-api/v1.json` is generated from reflection over the PSR-4 source tree and must match the
 * checked-in file byte for byte; run with `--write` only when a reviewed change deliberately accepts a new
 * surface. An enum's cases are recorded under `constants`, typed as the enum itself, so a case added or
 * removed is a recorded surface change like any other. `resources/capabilities/v1.json` and
 * `resources/service-map/v1.json` are authored by hand and held to the rules the Kumwe App adoption gate
 * applies: every capability names only exported symbols and existing documents, every exported symbol
 * belongs to a capability, an absent provider records its reason, and the three manifests agree on the
 * release the changelog records. `docs/public-api.md` must document every exported symbol and every public
 * member, enum cases included. The generated bytes carry no commit, timestamp or machine path, so the same
 * source produces identical output on every supported runtime.
 *
 * @since 0.1.0
 */

declare(strict_types=1);

const SEQUENCE_ROOT = __DIR__ . '/..';
const SEQUENCE_SOURCE = SEQUENCE_ROOT . '/src';
const SEQUENCE_PACKAGE = 'kumwe/sequence';
const SEQUENCE_NAMESPACE = 'Kumwe\\Sequence\\';
const SEQUENCE_PUBLIC_API = 'resources/public-api/v1.json';
const SEQUENCE_CAPABILITIES = 'resources/capabilities/v1.json';
const SEQUENCE_SERVICE_MAP = 'resources/service-map/v1.json';
const SEQUENCE_CHANGELOG = 'CHANGELOG.md';
const SEQUENCE_API_DOCUMENT = 'docs/public-api.md';
const SEQUENCE_CAPABILITY_PREFIX = 'sequence.';
const SEQUENCE_LIFETIMES = ['shared', 'non-shared', 'request-supplied'];

/** @var list<string> $arguments */
$arguments = $_SERVER['argv'] ?? [];

try {
    exit(sequenceManifestsMain($arguments));
} catch (Throwable $error) {
    fwrite(STDERR, "Manifest verification failed: {$error->getMessage()}\n");
    exit(1);
}

/**
 * Generate the public API manifest, verify or record it, then verify the hand-authored manifests and docs.
 *
 * @param   list<string>  $arguments  Command name followed by no option or --write.
 *
 * @return  int  Process status.
 *
 * @since   0.1.0
 */
function sequenceManifestsMain(array $arguments): int
{
    $options = array_slice($arguments, 1);
    if ($options !== [] && $options !== ['--write']) {
        fwrite(STDERR, "Usage: php tools/verify-manifests.php [--write]\n");

        return 2;
    }

    sequenceRegisterAutoloader();
    $release = sequenceRecordedRelease();
    $symbols = sequenceReflectedSymbols();
    $manifest = sequencePublicApiManifest($symbols, $release);
    $bytes = json_encode(
        $manifest,
        JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR,
    ) . "\n";

    if ($options === ['--write']) {
        sequenceWriteFile(SEQUENCE_PUBLIC_API, $bytes);
        fwrite(STDOUT, sprintf(
            "Public API manifest recorded: %d symbols for release %s written to %s.\n",
            count($symbols),
            $release,
            SEQUENCE_PUBLIC_API,
        ));
    } elseif (!is_file(sequencePath(SEQUENCE_PUBLIC_API))) {
        fwrite(STDERR, "The public API manifest is missing; review the generated surface, then run --write.\n");

        return 1;
    } else {
        $recorded = sequenceReadFile(SEQUENCE_PUBLIC_API);
        if ($recorded !== $bytes) {
            sequenceReportDifference($recorded, $bytes);

            return 1;
        }
    }

    $exported = array_keys($symbols);
    $capabilities = sequenceVerifyCapabilities($exported, $release);
    $provider = sequenceVerifyServiceMap($exported, $release);
    sequenceVerifyDocumentation($symbols);

    fwrite(STDOUT, sprintf(
        "Package manifests verified: %d public symbols, %d capabilities, %s, release %s documented.\n",
        count($symbols),
        $capabilities,
        $provider,
        $release,
    ));

    return 0;
}

/**
 * Register the package's dependency-free PSR-4 loader.
 *
 * @return  void
 *
 * @since   0.1.0
 */
function sequenceRegisterAutoloader(): void
{
    spl_autoload_register(static function (string $class): void {
        if (!str_starts_with($class, SEQUENCE_NAMESPACE)) {
            return;
        }
        $relative = substr($class, strlen(SEQUENCE_NAMESPACE));
        $path = SEQUENCE_SOURCE . '/' . str_replace('\\', '/', $relative) . '.php';
        if (is_file($path)) {
            require $path;
        }
    });
}

/**
 * Read the release the changelog records: the newest `## X.Y.Z` heading, skipping an unreleased section.
 *
 * @return  string  The recorded semantic version.
 *
 * @throws  RuntimeException  When the newest heading is not a release record or none exists.
 *
 * @since   0.1.0
 */
function sequenceRecordedRelease(): string
{
    $lines = preg_split('/\R/', sequenceReadFile(SEQUENCE_CHANGELOG));
    foreach ($lines === false ? [] : $lines as $line) {
        if (!str_starts_with($line, '## ')) {
            continue;
        }
        if ($line === '## Unreleased' || $line === '## [Unreleased]') {
            continue;
        }
        if (preg_match('/^## \[?([0-9]+\.[0-9]+\.[0-9]+)\]?( .*)?$/', $line, $match) === 1) {
            return $match[1];
        }
        throw new RuntimeException('The newest CHANGELOG.md heading is not a release record: ' . $line);
    }

    throw new RuntimeException('CHANGELOG.md records no release.');
}

/**
 * Discover every exported PSR-4 type declared by the source tree.
 *
 * One class-like declaration per PSR-4 file is the package's source convention; a file that does not
 * resolve under it fails closed. A declaration whose documentation block carries `@internal` is not
 * exported.
 *
 * @return  array<string, ReflectionClass<object>>  Reflections keyed by canonical name, sorted.
 *
 * @throws  RuntimeException  When the source directory is missing, a file declares no type or none is exported.
 *
 * @since   0.1.0
 */
function sequenceReflectedSymbols(): array
{
    if (!is_dir(SEQUENCE_SOURCE)) {
        throw new RuntimeException('The source directory is missing.');
    }

    $paths = [];
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator(SEQUENCE_SOURCE, FilesystemIterator::SKIP_DOTS),
    );
    foreach ($iterator as $file) {
        if ($file instanceof SplFileInfo && $file->isFile() && $file->getExtension() === 'php') {
            $paths[] = $file->getPathname();
        }
    }
    sort($paths, SORT_STRING);

    $symbols = [];
    foreach ($paths as $path) {
        $relative = substr($path, strlen(SEQUENCE_SOURCE) + 1, -4);
        $name = SEQUENCE_NAMESPACE . str_replace('/', '\\', $relative);
        $reflection = sequenceReflect($name);
        if ($reflection === null) {
            throw new RuntimeException(sprintf(
                '%s does not declare its expected PSR-4 type %s.',
                sequenceRelativePath($path),
                $name,
            ));
        }
        $comment = $reflection->getDocComment();
        if (is_string($comment) && preg_match('/^\s*\*\s*@internal\b/m', $comment) === 1) {
            continue;
        }
        $symbols[$reflection->getName()] = $reflection;
    }
    ksort($symbols, SORT_STRING);

    if ($symbols === []) {
        throw new RuntimeException('The public API cannot be empty.');
    }

    return $symbols;
}

/**
 * Reflect a class-like name once it is known to exist.
 *
 * @param   string  $name  Canonical name.
 *
 * @return  ReflectionClass<object>|null  The reflection, or null when no such type can be loaded.
 *
 * @since   0.1.0
 */
function sequenceReflect(string $name): ?ReflectionClass
{
    if (class_exists($name) || interface_exists($name) || trait_exists($name) || enum_exists($name)) {
        return new ReflectionClass($name);
    }

    return null;
}

/**
 * Render the complete public API manifest in the Kumwe App schema shape.
 *
 * @param   array<string, ReflectionClass<object>>  $symbols  Exported symbols, sorted.
 * @param   string                                  $release  Release the changelog records.
 *
 * @return  array<string, mixed>  Deterministic manifest document.
 *
 * @since   0.1.0
 */
function sequencePublicApiManifest(array $symbols, string $release): array
{
    $entries = [];
    $extensionPoints = [];
    foreach ($symbols as $name => $reflection) {
        $entries[$name] = sequenceSymbol($reflection);
        if ($reflection->isInterface() || ($reflection->isAbstract() && !$reflection->isEnum())) {
            $extensionPoints[] = $name;
        }
    }

    return [
        'schema' => 'kumwe-package-public-api/v1',
        'package' => SEQUENCE_PACKAGE,
        'release' => $release,
        'namespace' => SEQUENCE_NAMESPACE,
        'symbols' => (object) $entries,
        'extension_points' => $extensionPoints,
        'digest_of' => 'src',
    ];
}

/**
 * Render one class-like declaration and only the public members it declares.
 *
 * @param   ReflectionClass<object>  $type  Reflected canonical declaration.
 *
 * @return  array<string, mixed>  Compatibility-relevant surface.
 *
 * @throws  RuntimeException  When the declaration does not come from a file inside the repository.
 *
 * @since   0.1.0
 */
function sequenceSymbol(ReflectionClass $type): array
{
    $name = $type->getName();
    $parent = $type->getParentClass();
    $interfaces = $type->getInterfaceNames();
    sort($interfaces, SORT_STRING);
    $kind = 'class';
    if ($type->isEnum()) {
        $kind = 'enum';
    } elseif ($type->isInterface()) {
        $kind = 'interface';
    } elseif ($type->isTrait()) {
        $kind = 'trait';
    }

    $file = $type->getFileName();
    $rootPath = realpath(SEQUENCE_ROOT);
    $declaredIn = is_string($file) ? realpath($file) : false;
    if (!is_string($rootPath) || !is_string($declaredIn) || !str_starts_with($declaredIn, $rootPath . '/')) {
        throw new RuntimeException($name . ' is not declared by a file inside the repository.');
    }

    $stability = 'stable';
    $deprecated = null;
    $comment = $type->getDocComment();
    if (is_string($comment) && preg_match('/^\s*\*\s*@deprecated\b[ \t]*(.*)$/m', $comment, $match) === 1) {
        $stability = 'deprecated';
        $deprecated = ['since' => trim($match[1]) === '' ? 'unrecorded' : trim($match[1]), 'replacement' => null];
    }

    return [
        'kind' => $kind,
        'stability' => $stability,
        'file' => str_replace('\\', '/', substr($declaredIn, strlen($rootPath) + 1)),
        'abstract' => $type->isAbstract() && !$type->isInterface(),
        'final' => $type->isFinal(),
        'readonly' => $type->isReadOnly(),
        'parent' => $parent === false ? null : $parent->getName(),
        'interfaces' => $interfaces,
        'constants' => sequenceConstants($type, $name),
        'properties' => sequenceProperties($type, $name),
        'methods' => sequenceMethods($type, $name),
        'deprecated' => $deprecated,
    ];
}

/**
 * Render the public constants a type declares itself; an enum's cases are recorded typed as the enum.
 *
 * @param   ReflectionClass<object>  $type   Reflected declaration.
 * @param   class-string             $owner  Canonical declaring name.
 *
 * @return  stdClass  Constants keyed by name; empty when there are none.
 *
 * @since   0.1.0
 */
function sequenceConstants(ReflectionClass $type, string $owner): stdClass
{
    $constants = [];
    foreach ($type->getReflectionConstants(ReflectionClassConstant::IS_PUBLIC) as $constant) {
        if ($constant->getDeclaringClass()->getName() !== $owner) {
            continue;
        }
        if ($constant->isEnumCase()) {
            $constants[$constant->getName()] = ['type' => $owner];
            continue;
        }
        $constantType = $constant->getType();
        $constants[$constant->getName()] = [
            'type' => $constantType === null ? null : sequenceType($constantType, $owner),
        ];
    }
    ksort($constants, SORT_STRING);

    return (object) $constants;
}

/**
 * Render the public properties a type declares itself.
 *
 * @param   ReflectionClass<object>  $type   Reflected declaration.
 * @param   class-string             $owner  Canonical declaring name.
 *
 * @return  stdClass  Properties keyed by name; empty when there are none.
 *
 * @since   0.1.0
 */
function sequenceProperties(ReflectionClass $type, string $owner): stdClass
{
    $properties = [];
    foreach ($type->getProperties(ReflectionProperty::IS_PUBLIC) as $property) {
        if ($property->getDeclaringClass()->getName() !== $owner) {
            continue;
        }
        if ($type->isEnum() && in_array($property->getName(), ['name', 'value'], true)) {
            continue;
        }
        $propertyType = $property->getType();
        $properties[$property->getName()] = [
            'type' => $propertyType === null ? null : sequenceType($propertyType, $owner),
            'static' => $property->isStatic(),
            'readonly' => $property->isReadOnly(),
        ];
    }
    ksort($properties, SORT_STRING);

    return (object) $properties;
}

/**
 * Render the public methods a type declares itself, engine-synthesized enum methods excluded.
 *
 * @param   ReflectionClass<object>  $type   Reflected declaration.
 * @param   class-string             $owner  Canonical declaring name.
 *
 * @return  stdClass  Methods keyed by name; empty when there are none.
 *
 * @since   0.1.0
 */
function sequenceMethods(ReflectionClass $type, string $owner): stdClass
{
    $methods = [];
    foreach ($type->getMethods(ReflectionMethod::IS_PUBLIC) as $method) {
        if ($method->getDeclaringClass()->getName() !== $owner) {
            continue;
        }
        if ($type->isEnum() && in_array($method->getName(), ['cases', 'from', 'tryFrom'], true)) {
            continue;
        }
        $parameters = [];
        foreach ($method->getParameters() as $parameter) {
            $parameterType = $parameter->getType();
            $parameters[] = [
                'name' => $parameter->getName(),
                'type' => $parameterType === null ? null : sequenceType($parameterType, $owner),
                'optional' => $parameter->isOptional(),
                'variadic' => $parameter->isVariadic(),
                'by_reference' => $parameter->isPassedByReference(),
            ];
        }
        $returnType = $method->getReturnType();
        $methods[$method->getName()] = [
            'visibility' => 'public',
            'static' => $method->isStatic(),
            'parameters' => $parameters,
            'return' => $returnType === null ? null : sequenceType($returnType, $owner),
        ];
    }
    ksort($methods, SORT_STRING);

    return (object) $methods;
}

/**
 * Render a named, union or intersection type without import abbreviations.
 *
 * @param   ReflectionType  $type   Reflected declaration type.
 * @param   class-string    $owner  Canonical declaring name used to resolve relative types.
 *
 * @return  string  Canonical type expression.
 *
 * @throws  RuntimeException  When a relative parent type has no parent or the type kind is unknown.
 *
 * @since   0.1.0
 */
function sequenceType(ReflectionType $type, string $owner): string
{
    if ($type instanceof ReflectionNamedType) {
        $name = $type->getName();
        if ($name === 'self' || $name === 'static') {
            $name = $owner;
        } elseif ($name === 'parent') {
            $parent = get_parent_class($owner);
            if ($parent === false) {
                throw new RuntimeException("Relative parent type on {$owner} has no parent class.");
            }
            $name = $parent;
        }

        return $type->allowsNull() && !in_array($name, ['mixed', 'null'], true) ? '?' . $name : $name;
    }
    if ($type instanceof ReflectionUnionType) {
        return implode('|', array_map(
            static fn (ReflectionType $member): string => sequenceType($member, $owner),
            $type->getTypes(),
        ));
    }
    if ($type instanceof ReflectionIntersectionType) {
        return implode('&', array_map(
            static fn (ReflectionType $member): string => sequenceType($member, $owner),
            $type->getTypes(),
        ));
    }

    throw new RuntimeException('Unknown reflection type kind ' . $type::class . '.');
}

/**
 * Hold the capabilities manifest to the adoption gate's rules and prove it covers every exported symbol.
 *
 * @param   list<string>  $exported  Exported canonical names.
 * @param   string        $release   Release the changelog records.
 *
 * @return  int  Number of capabilities declared.
 *
 * @throws  RuntimeException  When the manifest disagrees with the source tree, the changelog or the docs.
 *
 * @since   0.1.0
 */
function sequenceVerifyCapabilities(array $exported, string $release): int
{
    $file = SEQUENCE_CAPABILITIES;
    $document = sequenceJsonObject($file);
    sequenceExpect($document, 'schema', 'kumwe-package-capabilities/v1', $file);
    sequenceExpect($document, 'package', SEQUENCE_PACKAGE, $file);
    sequenceExpect($document, 'release', $release, $file);
    sequenceExpect($document, 'namespace', SEQUENCE_NAMESPACE, $file);
    sequenceExpectText($document, 'responsibility', $file);
    if (!is_array($document['non_responsibilities'] ?? null)) {
        throw new RuntimeException($file . ' must list non_responsibilities.');
    }
    if (!array_key_exists('native_requirements', $document) || $document['native_requirements'] !== null) {
        throw new RuntimeException($file . ' must record native_requirements as null: no extension is needed.');
    }

    $capabilities = $document['capabilities'] ?? null;
    if (!is_array($capabilities) || $capabilities === []) {
        throw new RuntimeException($file . ' declares no capability.');
    }
    $seen = [];
    $covered = [];
    foreach ($capabilities as $capability) {
        if (!is_array($capability)) {
            throw new RuntimeException($file . ' carries a malformed capability entry.');
        }
        $id = $capability['id'] ?? null;
        if (
            !is_string($id)
            || preg_match('/^[a-z0-9-]+(\.[a-z0-9-]+)+$/', $id) !== 1
            || !str_starts_with($id, SEQUENCE_CAPABILITY_PREFIX)
        ) {
            throw new RuntimeException($file . ' carries a capability id outside the sequence.* form.');
        }
        if (isset($seen[$id])) {
            throw new RuntimeException($file . ' declares the capability ' . $id . ' twice.');
        }
        $seen[$id] = true;
        sequenceExpectText($capability, 'title', $file . ' capability ' . $id);
        sequenceExpectText($capability, 'description', $file . ' capability ' . $id);
        $symbols = $capability['symbols'] ?? null;
        if (!is_array($symbols) || $symbols === []) {
            throw new RuntimeException($file . ' capability ' . $id . ' names no symbol.');
        }
        foreach ($symbols as $symbol) {
            if (!is_string($symbol) || !in_array($symbol, $exported, true)) {
                throw new RuntimeException(sprintf(
                    '%s capability %s names %s, which the public API manifest does not export.',
                    $file,
                    $id,
                    is_string($symbol) ? $symbol : 'a non-string',
                ));
            }
            $covered[$symbol] = true;
        }
        $documents = $capability['documentation'] ?? null;
        if (!is_array($documents)) {
            throw new RuntimeException($file . ' capability ' . $id . ' has no documentation list.');
        }
        foreach ($documents as $document_) {
            if (!is_string($document_) || !is_file(sequencePath($document_))) {
                throw new RuntimeException($file . ' capability ' . $id . ' links a document that does not exist.');
            }
        }
    }
    foreach ($exported as $symbol) {
        if (!isset($covered[$symbol])) {
            throw new RuntimeException(sprintf('%s exports %s but no capability claims it.', $file, $symbol));
        }
    }

    $deprecations = $document['deprecations'] ?? null;
    if (!is_array($deprecations)) {
        throw new RuntimeException($file . ' must carry a deprecations list.');
    }
    foreach ($deprecations as $deprecation) {
        $symbol = is_array($deprecation) ? ($deprecation['symbol'] ?? null) : null;
        if (!is_string($symbol) || !in_array($symbol, $exported, true)) {
            throw new RuntimeException($file . ' deprecates a symbol the public API manifest does not export.');
        }
    }

    return count($seen);
}

/**
 * Hold the service map to the adoption gate's rules: a provider needs factories, its absence needs a reason.
 *
 * @param   list<string>  $exported  Exported canonical names.
 * @param   string        $release   Release the changelog records.
 *
 * @return  string  One-line summary of the provider decision.
 *
 * @throws  RuntimeException  When the map is inconsistent or names an unexported symbol.
 *
 * @since   0.1.0
 */
function sequenceVerifyServiceMap(array $exported, string $release): string
{
    $file = SEQUENCE_SERVICE_MAP;
    $document = sequenceJsonObject($file);
    sequenceExpect($document, 'schema', 'kumwe-package-service-map/v1', $file);
    sequenceExpect($document, 'package', SEQUENCE_PACKAGE, $file);
    sequenceExpect($document, 'release', $release, $file);
    if (!array_key_exists('config_provider', $document)) {
        throw new RuntimeException($file . ' must record config_provider, as a name or null.');
    }
    $provider = $document['config_provider'];
    $factories = $document['factories'] ?? null;
    if (!is_array($factories)) {
        throw new RuntimeException($file . ' must carry a factories list.');
    }

    if ($provider === null) {
        sequenceExpectText($document, 'provider_absence_reason', $file);
        if ($factories !== []) {
            throw new RuntimeException($file . ' declares factories without a provider.');
        }
        $summary = 'no provider (reason recorded)';
    } else {
        if (!is_string($provider) || !in_array($provider, $exported, true)) {
            throw new RuntimeException($file . ' names a config_provider the public API manifest does not export.');
        }
        if ($factories === []) {
            throw new RuntimeException($file . ' declares a config_provider without any factory.');
        }
        $summary = 'provider ' . $provider;
    }

    $services = [];
    foreach ($factories as $factory) {
        if (!is_array($factory)) {
            throw new RuntimeException($file . ' carries a malformed factory entry.');
        }
        foreach (['service', 'factory'] as $field) {
            $symbol = $factory[$field] ?? null;
            if (!is_string($symbol) || !in_array($symbol, $exported, true)) {
                throw new RuntimeException($file . ' factory ' . $field . ' is not an exported public symbol.');
            }
        }
        if (!in_array($factory['lifetime'] ?? null, SEQUENCE_LIFETIMES, true)) {
            throw new RuntimeException($file . ' factory lifetime is not shared, non-shared or request-supplied.');
        }
        $service = $factory['service'];
        if (is_string($service)) {
            if (isset($services[$service])) {
                throw new RuntimeException($file . ' gives service ' . $service . ' two factories.');
            }
            $services[$service] = true;
        }
    }

    $aliases = $document['aliases'] ?? null;
    if (!is_array($aliases)) {
        throw new RuntimeException($file . ' must carry an aliases map.');
    }
    foreach ($aliases as $alias => $target) {
        if (!is_string($alias) || !is_string($target)) {
            throw new RuntimeException($file . ' carries a malformed alias.');
        }
        foreach ([$alias, $target] as $symbol) {
            if (!in_array($symbol, $exported, true)) {
                throw new RuntimeException($file . ' alias ' . $alias . ' names an unexported symbol.');
            }
        }
        if (isset($services[$alias])) {
            throw new RuntimeException($file . ' registers ' . $alias . ' as both a service and an alias.');
        }
    }
    if (!is_array($document['delegators'] ?? null)) {
        throw new RuntimeException($file . ' must carry a delegators list.');
    }
    $keys = $document['configuration_keys'] ?? null;
    if (!is_array($keys)) {
        throw new RuntimeException($file . ' must carry a configuration_keys list.');
    }
    foreach ($keys as $entry) {
        $key = is_array($entry) ? ($entry['key'] ?? null) : null;
        if (!is_string($key) || preg_match('/^kumwe\.sequence(\.[A-Za-z0-9_.-]+)+$/', $key) !== 1) {
            throw new RuntimeException($file . ' carries a configuration key outside kumwe.sequence.*.');
        }
        if (!is_array($entry) || !array_key_exists('default', $entry) || !is_string($entry['description'] ?? null)) {
            throw new RuntimeException($file . ' configuration key ' . $key . ' lacks a default or a description.');
        }
    }

    return $summary;
}

/**
 * Prove `docs/public-api.md` carries a section per exported symbol naming every public member it declares.
 *
 * @param   array<string, ReflectionClass<object>>  $symbols  Exported symbols.
 *
 * @return  void
 *
 * @throws  RuntimeException  When a symbol section or a member mention is missing.
 *
 * @since   0.1.0
 */
function sequenceVerifyDocumentation(array $symbols): void
{
    $document = sequenceReadFile(SEQUENCE_API_DOCUMENT);
    $sections = preg_split('/^(?=## )/m', $document);
    $sections = $sections === false ? [] : $sections;

    foreach ($symbols as $name => $reflection) {
        $section = null;
        foreach ($sections as $candidate) {
            $heading = explode("\n", $candidate, 2)[0];
            if (str_starts_with($heading, '## ') && str_contains($heading, '`' . $name . '`')) {
                $section = $candidate;
                break;
            }
        }
        if ($section === null) {
            throw new RuntimeException(sprintf('%s has no "## `%s`" section.', SEQUENCE_API_DOCUMENT, $name));
        }
        foreach ($reflection->getMethods(ReflectionMethod::IS_PUBLIC) as $method) {
            if ($method->getDeclaringClass()->getName() !== $name) {
                continue;
            }
            if ($reflection->isEnum() && in_array($method->getName(), ['cases', 'from', 'tryFrom'], true)) {
                continue;
            }
            if (!str_contains($section, '`' . $method->getName() . '(')) {
                throw new RuntimeException(sprintf(
                    '%s documents %s without its method %s().',
                    SEQUENCE_API_DOCUMENT,
                    $name,
                    $method->getName(),
                ));
            }
        }
        foreach ($reflection->getReflectionConstants(ReflectionClassConstant::IS_PUBLIC) as $constant) {
            if ($constant->getDeclaringClass()->getName() !== $name) {
                continue;
            }
            if (!str_contains($section, '`' . $constant->getName() . '`')) {
                throw new RuntimeException(sprintf(
                    '%s documents %s without its %s %s.',
                    SEQUENCE_API_DOCUMENT,
                    $name,
                    $constant->isEnumCase() ? 'case' : 'constant',
                    $constant->getName(),
                ));
            }
        }
        foreach ($reflection->getProperties(ReflectionProperty::IS_PUBLIC) as $property) {
            if ($property->getDeclaringClass()->getName() !== $name) {
                continue;
            }
            if ($reflection->isEnum() && in_array($property->getName(), ['name', 'value'], true)) {
                continue;
            }
            if (!str_contains($section, '`$' . $property->getName() . '`')) {
                throw new RuntimeException(sprintf(
                    '%s documents %s without its property $%s.',
                    SEQUENCE_API_DOCUMENT,
                    $name,
                    $property->getName(),
                ));
            }
        }
    }
}

/**
 * Report the first semantic difference between the recorded and the generated public API manifest.
 *
 * @param   string  $recordedBytes   Checked-in manifest bytes.
 * @param   string  $generatedBytes  Freshly generated manifest bytes.
 *
 * @return  void
 *
 * @since   0.1.0
 */
function sequenceReportDifference(string $recordedBytes, string $generatedBytes): void
{
    $recorded = json_decode($recordedBytes, true);
    $generated = json_decode($generatedBytes, true);
    if (!is_array($recorded)) {
        fwrite(STDERR, "The recorded public API manifest is not valid JSON.\n");

        return;
    }
    $difference = sequenceFirstDifference($recorded, $generated);
    if ($difference === null) {
        fwrite(
            STDERR,
            "The public API manifest is semantically current but not canonical JSON; run --write to normalize.\n",
        );

        return;
    }
    fwrite(STDERR, sprintf(
        "The public API manifest drifted at %s.\nRecorded:  %s\nGenerated: %s\n"
            . "Treat an incompatible change as a new major; run --write only after compatibility review.\n",
        $difference['path'],
        sequenceDisplay($difference['recorded']),
        sequenceDisplay($difference['generated']),
    ));
}

/**
 * Find the first semantic difference between two decoded manifest values.
 *
 * @param   mixed   $recorded   Checked-in value.
 * @param   mixed   $generated  Generated value.
 * @param   string  $path       JSONPath-like location.
 *
 * @return  array{path: string, recorded: mixed, generated: mixed}|null  First difference, or null when equal.
 *
 * @since   0.1.0
 */
function sequenceFirstDifference(mixed $recorded, mixed $generated, string $path = '$'): ?array
{
    if (!is_array($recorded) || !is_array($generated)) {
        return $recorded === $generated
            ? null
            : ['path' => $path, 'recorded' => $recorded, 'generated' => $generated];
    }
    $keys = array_values(array_unique([...array_keys($recorded), ...array_keys($generated)], SORT_REGULAR));
    foreach ($keys as $key) {
        $memberPath = is_int($key) ? $path . '[' . $key . ']' : $path . '.' . $key;
        if (!array_key_exists($key, $recorded)) {
            return ['path' => $memberPath, 'recorded' => '<absent>', 'generated' => $generated[$key]];
        }
        if (!array_key_exists($key, $generated)) {
            return ['path' => $memberPath, 'recorded' => $recorded[$key], 'generated' => '<absent>'];
        }
        $difference = sequenceFirstDifference($recorded[$key], $generated[$key], $memberPath);
        if ($difference !== null) {
            return $difference;
        }
    }

    return null;
}

/**
 * Render a difference value on one line.
 *
 * @param   mixed  $value  Difference member.
 *
 * @return  string  JSON where possible, PHP export otherwise.
 *
 * @since   0.1.0
 */
function sequenceDisplay(mixed $value): string
{
    $encoded = json_encode($value, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

    return $encoded === false ? var_export($value, true) : $encoded;
}

/**
 * Require a field to equal an expected string.
 *
 * @param   array<string, mixed>  $document  Decoded manifest.
 * @param   string                $field     Field name.
 * @param   string                $expected  Required value.
 * @param   string                $file      Manifest path for the message.
 *
 * @return  void
 *
 * @throws  RuntimeException  When the field is absent or differs.
 *
 * @since   0.1.0
 */
function sequenceExpect(array $document, string $field, string $expected, string $file): void
{
    if (($document[$field] ?? null) !== $expected) {
        throw new RuntimeException(sprintf('%s must record %s as %s.', $file, $field, $expected));
    }
}

/**
 * Require a field to be a non-empty string.
 *
 * @param   array<int|string, mixed>  $document  Decoded manifest or entry.
 * @param   string                    $field     Field name.
 * @param   string                    $where     Location for the message.
 *
 * @return  void
 *
 * @throws  RuntimeException  When the field is absent, not a string or blank.
 *
 * @since   0.1.0
 */
function sequenceExpectText(array $document, string $field, string $where): void
{
    $value = $document[$field] ?? null;
    if (!is_string($value) || trim($value) === '') {
        throw new RuntimeException(sprintf('%s must carry a non-empty %s.', $where, $field));
    }
}

/**
 * Decode one JSON object file under the repository root.
 *
 * @param   string  $relative  Repository-relative path.
 *
 * @return  array<string, mixed>  The decoded object.
 *
 * @throws  RuntimeException  When the file is unreadable or not a JSON object.
 *
 * @since   0.1.0
 */
function sequenceJsonObject(string $relative): array
{
    try {
        $decoded = json_decode(sequenceReadFile($relative), true, 512, JSON_THROW_ON_ERROR);
    } catch (JsonException $error) {
        throw new RuntimeException($relative . ' is not valid JSON: ' . $error->getMessage(), 0, $error);
    }
    if (!is_array($decoded) || array_is_list($decoded)) {
        throw new RuntimeException($relative . ' is not a JSON object.');
    }
    $object = [];
    foreach ($decoded as $key => $value) {
        $object[(string) $key] = $value;
    }

    return $object;
}

/**
 * Resolve a repository-relative path.
 *
 * @param   string  $relative  Repository-relative path.
 *
 * @return  string  Absolute path.
 *
 * @since   0.1.0
 */
function sequencePath(string $relative): string
{
    return SEQUENCE_ROOT . '/' . $relative;
}

/**
 * Read one repository file completely.
 *
 * @param   string  $relative  Repository-relative path.
 *
 * @return  string  File bytes.
 *
 * @throws  RuntimeException  When the file is missing or unreadable.
 *
 * @since   0.1.0
 */
function sequenceReadFile(string $relative): string
{
    $path = sequencePath($relative);
    $bytes = is_file($path) ? file_get_contents($path) : false;
    if (!is_string($bytes)) {
        throw new RuntimeException('Cannot read ' . $relative . '.');
    }

    return $bytes;
}

/**
 * Atomically replace one repository file.
 *
 * @param   string  $relative  Repository-relative path.
 * @param   string  $bytes     Complete new contents.
 *
 * @return  void
 *
 * @throws  RuntimeException  When the directory or the file cannot be written.
 *
 * @since   0.1.0
 */
function sequenceWriteFile(string $relative, string $bytes): void
{
    $path = sequencePath($relative);
    $directory = dirname($path);
    if (!is_dir($directory) && !mkdir($directory, 0777, true) && !is_dir($directory)) {
        throw new RuntimeException('Cannot create the directory of ' . $relative . '.');
    }
    $temporary = tempnam($directory, '.manifest-');
    if ($temporary === false) {
        throw new RuntimeException('Cannot create a temporary file for ' . $relative . '.');
    }
    try {
        if (file_put_contents($temporary, $bytes, LOCK_EX) !== strlen($bytes)) {
            throw new RuntimeException('Cannot write the complete ' . $relative . '.');
        }
        if (!rename($temporary, $path)) {
            throw new RuntimeException('Cannot replace ' . $relative . ' atomically.');
        }
    } finally {
        if (is_file($temporary)) {
            unlink($temporary);
        }
    }
}

/**
 * Spell a repository path without environment-specific prefixes.
 *
 * @param   string  $path  Absolute repository path.
 *
 * @return  string  Slash-normalized relative path.
 *
 * @since   0.1.0
 */
function sequenceRelativePath(string $path): string
{
    $rootPath = realpath(SEQUENCE_ROOT);
    $real = realpath($path);
    if (is_string($rootPath) && is_string($real) && str_starts_with($real, $rootPath . '/')) {
        return str_replace('\\', '/', substr($real, strlen($rootPath) + 1));
    }

    return basename($path);
}
